export const manufacturers = [
  'Abarth',
  'Acura',
  'Aixam',
  'Alfa Romeo',
  'Alpina',
  'Alpine',
  'Alvis',
  'AMC',
  'ARO',
  'Artega',
  'Ascari',
  'Aston Martin',
  'Audi',
  'Austin',
  'Austin-Healey',
  'Auto Union',
  'Autobacs',
  'Autobianchi',
  'Axon',
  'BAC',
  'Bailey',
  'Bentley',
  'BMW',
  'Bolwell',
  'Borgward',
  'Brabham',
  'Brabus',
  'Brabham',
  'Bricklin',
  'Bristol',
  'Bugatti',
  'Buick',
  'BYD',
  'Cadillac',
  'Callaway',
  'Caparo',
  'Caterham',
  'Chery',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Cizeta',
  'Cobra',
  'Comarth',
  'Coda',
  'Coloni',
  'Commuter',
  'Cisitalia',
  'Covini',
  'Dacia',
  'Daewoo',
  'DAF',
  'Daihatsu',
  'Daimler',
  'Dallara',
  'Datsun',
  'De Tomaso',
  'Delage',
  'Delahaye',
  'DeLorean',
  'DeSoto',
  'Devon',
  'Diamond-Star Motors',
  'Dinan',
  'Dodge',
  'Donkervoort',
  'Drako',
  'DS Automobiles',
  'Eagle',
  'Edsel',
  'Elfin',
  'Elio Motors',
  'Excalibur',
  'Facel Vega',
  'Faraday Future',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Force',
  'Ford',
  'Fornasari',
  'Foton',
  'Franklin',
  'Frisky',
  'GAZ',
  'Geely',
  'Genesis',
  'Geo',
  'Gilbern',
  'Ginetta',
  'GMC',
  'Gumpert',
  'Haval',
  'Hennessey',
  'Hindustan Motors',
  'Hispano-Suiza',
  'Holden',
  'Honda',
  'Hongqi',
  'Hotchkiss',
  'HSV',
  'Hudson',
  'Hummer',
  'Hyundai',
  'IKA',
  'Infiniti',
  'Innocenti',
  'Inokom',
  'Intermeccanica',
  'Invicta',
  'Isdera',
  'Isuzu',
  'Iveco',
  'JAC',
  'Jaguar',
  'Jeep',
  'Jensen',
  'Joss',
  'Koenigsegg',
  'KTM',
  'Lada',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'LDV',
  'Lexus',
  'Leyland',
  'Lincoln',
  'Lloyd',
  'Locomobile',
  'Lonsdale',
  'Lotus',
  'Lutzmann',
  'Luxgen',
  'Lynk & Co',
  'Mahindra',
  'Marcos',
  'Marlin',
  'Maserati',
  'Matra',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mercury',
  'Merkur',
  'Messerschmitt',
  'MG',
  'Microcar',
  'Mini',
  'Mitsubishi',
  'Mitsuoka',
  'Monteverdi',
  'Moretti',
  'Morgan',
  'Morris',
  'Mosler',
  'Nardi',
  'Nash',
  'Noble',
  'NSU',
  'Ohta',
  'Oldsmobile',
  'Opel',
  'Osca',
  'Packard',
  'Pagani',
  'Panhard',
  'Panoz',
  'Panther',
  'Peerless',
  'Pegaso',
  'Perodua',
  'Peugeot',
  'Piaggio',
  'Pininfarina',
  'Plymouth',
  'Polaris',
  'Pontiac',
  'Porsche',
  'Premier',
  'Prodrive',
  'Proton',
  'Puch',
  'Qoros',
  'Radical',
  'Railton',
  'Ram',
  'Rambler',
  'Reliant',
  'Renault',
  'Rezvani',
  'Riley',
  'Rimac',
  'Rinspeed',
  'Roewe',
  'Rolls-Royce',
  'Rover',
  'Ruf',
  'Saab',
  'Saleen',
  'Samsung',
  'Saturn',
  'Scania',
  'Scion',
  'Seat',
  'Shelby',
  'Siata',
  'Simca',
  'Singer',
  'Skoda',
  'Smart',
  'Spyker',
  'SsangYong',
  'SSC',
  'Standard',
  'Sterling',
  'Studebaker',
  'Subaru',
  'Sunbeam',
  'Suzuki',
  'Swallow',
  'Talbot',
  'Tata',
  'Tatra',
  'Tazzari',
  'Tesla',
  'Think',
  'Toyota',
  'Trabant',
  'Triumph',
  'Tucker',
  'TVR',
  'Ultima',
  'Vanden Plas',
  'Vauxhall',
  'Vector',
  'Venturi',
  'Veritas',
  'Vespa',
  'Vignale',
  'Volkswagen',
  'Volvo',
  'VUHL',
  'W Motors',
  'Wartburg',
  'Westfield',
  'Willys',
  'Wolseley',
  'Zastava',
  'ZAZ',
  'Zenvo',
  'ZIL',
  'Zundapp',
  'Zil',
  'Zündapp',
]

export const yearsOfProduction = [
  { title: 'Year', value: '' },
  { title: '2015', value: '2015' },
  { title: '2016', value: '2016' },
  { title: '2017', value: '2017' },
  { title: '2018', value: '2018' },
  { title: '2019', value: '2019' },
  { title: '2020', value: '2020' },
  { title: '2021', value: '2021' },
  { title: '2022', value: '2022' },
  { title: '2023', value: '2023' },
]

export const fuels = [
  {
    title: 'Fuel',
    value: '',
  },
  {
    title: 'Gas',
    value: 'Gas',
  },
  {
    title: 'Electricity',
    value: 'Electricity',
  },
]

export const footerLinks = [
  {
    title: 'About',
    links: [
      { title: 'How it works', url: '/' },
      { title: 'Featured', url: '/' },
      { title: 'Partnership', url: '/' },
      { title: 'Bussiness Relation', url: '/' },
    ],
  },
  {
    title: 'Company',
    links: [
      { title: 'Events', url: '/' },
      { title: 'Blog', url: '/' },
      { title: 'Podcast', url: '/' },
      { title: 'Invite a friend', url: '/' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { title: 'Discord', url: '/' },
      { title: 'Instagram', url: '/' },
      { title: 'Twitter', url: '/' },
      { title: 'Facebook', url: '/' },
    ],
  },
]
